### ISSUE TITLE
[Infra] Slack channel setup with synchronization

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/github-analysis-report-2020#3]
Like `Wuhan2020` project, I think we can also use Slack as the IM tool for collaberation, and an independent workspace is mroe suitable.

Any suggestions ?

**Comment by frank-zsy** [comment]
Maybe, although the collaborate process may not be too fast, GitHub asynchronous communication is enough, but we also need a place to share our past research and works to help developers to catch up. Slack is a good choice.

**Comment by will-ww** [comment]
Yes, we don't need handl this in a rush way, and the `allspark-chaoss` workspace may also be a choice to support.

Creat a new one or use `allspark-chaoss` workspace, any suggestion ? @tianyi

**Comment by tianyichow** [comment]
All of our discussions in this workspace are not in  English. So developers can not understand Chinese will  not able to join the discussion. Maybe we need create a new workspace and  put all resources of our researches and works in English version.  "allspark-chaoss" workspace is just used for share ideas and documents in our lab.

**Comment by sunshinemingo** [comment]
I have created new workspace named `X-GitHub-Analysis`. Everyone can join in it using [this link](https://join.slack.com/t/x-github-analysis/shared_invite/zt-gz8ykv3l-qP53IpajsZIGsx6dFo_8Lg).(expires in 30 days)

**Comment by frank-zsy** [comment]
> I have created new workspace named `X-GitHub-Analysis`. Everyone can join in it using [this link](https://join.slack.com/t/x-github-analysis/shared_invite/zt-gz8ykv3l-qP53IpajsZIGsx6dFo_8Lg).(expires in 30 days)

Can you make a permanent link and add it into README?

**Comment by sunshinemingo** [comment]
![image](https://user-images.githubusercontent.com/37278844/91009887-14262500-e614-11ea-951c-1b5ea2e2444f.png)
The invite link settings have three choices, I don't find `Never Expired` option.

**Comment by frank-zsy** [comment]
OK, so slack just remove the feature, because I made a permanent link for Wuhan2020 earlier, something like that
![image](https://user-images.githubusercontent.com/8512426/91012612-f0191280-e618-11ea-831c-ebdb89cf44ef.png)
Which shows the link will expire in 1000years, but now it only has three options too, so we need to update the link every month.

**Comment by sunshinemingo** [comment]
OK, I will add the invite link into README and update it monthly.

**Comment by frank-zsy** [comment]
Closed by #29
