### ISSUE TITLE
[Docs] Add workflow for other types of commiting(besides sql)

### ISSUE THREAD

**Issue by sunshinemingo** [X-lab2017/github-analysis-report-2020#39]
We need a document to describe the workflow for commiting other files(excluding sql). Such as  if the PR contains `docs` in the title, the bot will add `area/document` label.

**Comment by frank-zsy** [comment]
We already support if PR title contains `docs` then add `area/document` label, I assume you mean that if the PR commit a file under `docs/` folder then add `area/document` label which will be much more accurate.

**Comment by sunshinemingo** [comment]
Yes, what you said is much more accurate. I mean that if developers commit document files , the bot will add `area/document` label. The document flie are mostly under `docs/`.

**Comment by frank-zsy** [comment]
OK, I will implement a common component in Hypertrons, which allows project to config like below:

```json
[
  {
    "fileRegex": "docs/.*",
    "label": "area/document"
  }
]
```

So we can easily config it for needs like this.
