### ISSUE TITLE
[Proposal] New committer proposal

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/github-analysis-report-2020#42]
As [`CONTRIBUTORS`](https://github.com/X-lab2017/github-analysis-report-2020/blob/master/CONTRIBUTORS) file shows, @sunshinemingo is quite active for past two weeks in project discussion, I propose @sunshinemingo to be our new committer to approve PR.

**Comment by will-ww** [comment]
+1 & congratulations~  @sunshinemingo

**Comment by sunshinemingo** [comment]
yeah～I will try my best do better and better.

**Comment by frank-zsy** [comment]
@sunshinemingo congrats, now it's your duty to review and `/approve` PRs.

**Comment by sunshinemingo** [comment]
OK，I get it!
